### PR TITLE
Load from css text

### PR DESCRIPTION
**Pull request by tralves**
This PR adds the function `applyThemeCss` that receives a string containing CSS and applies it.

The branch was created from commit e04f0a937a223363828a99b0bf45616d68529670 (the version published in npm) because the code in master didn't work.

I created the sample project [ns-vue-theme-swap-sample](https://github.com/tralves/ns-vue-theme-swap-sample). In this project, I implemented theme swapping with both the existing method `applyTheme` and the new method `applyThemeCss` to show that I didn't ruin the current functionality.

The file `themes.js` had both tabs and spaces, so I went ahead an prettyfied it... sorry...

### CODE REVIEW

**Comment by NathanaelA** [comment]
I went to do this the other day; and it is in conflict with the existing file.  Can you resolve the conflicts so it is easy to merge.

**Comment by tralves** [comment]
I think it mostly has to do with the fact that I had to grab a previous version (the version published on npm). I couldn't make it work with the version currently on master. Is it a WIP? Can we go back to the previous version, or make an effort make the latest version work?

**Comment by NathanaelA** [comment]
The current version should be what works properly.  I'm not sure why the current version shouldn't be working for you.

**Comment by tralves** [comment]
It had something to do with missing dependencies. I'll look deeper into it. Also, the latest version is not the one published in npm.

**Comment by NathanaelA** [comment]
Ok, that is weird.  NPM should be in sync with github.   I try and keep them in sync...    I'll look into that.

**Comment by NathanaelA** [comment]
Closing because of #6

**Pull request closed without merging**
